services:
  nginx:
    container_name: nginx
    build:
      labels:
        - inception-nginx:latest
      context: ./requirements/nginx/.
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:443
    volumes:
      - shared:/var/www/html/
    networks:
      - ${DOCKER_NETWORK}
    env_file:
      - .env
    depends_on:
      wordpress:
        condition: service_healthy

  wordpress:
    container_name: wordpress-php
    build:
      labels:
        - inception-wordpress=latest
      context: ./requirements/wordpress/.
    restart: unless-stopped
    volumes:
      - shared:/var/www/html/
    healthcheck:
      test: [ "CMD", "wp", "healthcheck", "server", "--allow-root" ]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - ${DOCKER_NETWORK}
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    container_name: mariadb
    build:
      labels:
        - inception-mariadb:latest
      context: ./requirements/mariadb/.
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-u", "$MYSQL_USER", "-p$MYSQL_USER", "--silent" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 2s
    volumes:
      - database:/var/lib/mysql/
    networks:
      - ${DOCKER_NETWORK}
    env_file:
      - .env

volumes:
  shared:
    driver_opts:
      type: none
      device: ${DOCKER_SHARED_VOLUME_PATH}
      o: bind
  database:
    driver_opts:
      type: none
      device: ${DOCKER_DB_VOLUME_PATH}
      o: bind

networks:
  inception:
    name: ${DOCKER_NETWORK}
    driver: bridge
