services:
  nginx:
    container_name: nginx
    build:
      labels:
        - inception-nginx:latest
      context: ./requirements/nginx/.
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:443
    volumes:
      - shared:/var/www/html/
    networks:
      - ${DOCKER_NETWORK}
    env_file:
      - .env
    depends_on:
      wordpress:
        condition: service_healthy

  wordpress:
    container_name: wordpress-php
    build:
      labels:
        - inception-wordpress=latest
      context: ./requirements/wordpress/.
    restart: unless-stopped
    ports:
      - ${WORDPRESS_PORT}:9000
    volumes:
      - shared:/var/www/html/
    healthcheck:
      test: [ "CMD", "wp", "healthcheck", "server", "--allow-root" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 2s
    networks:
      - ${DOCKER_NETWORK}
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    container_name: mariadb
    build:
      labels:
        - inception-mariadb:latest
      context: ./requirements/mariadb/.
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 2s
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - ${DOCKER_NETWORK}
    env_file:
      - .env

volumes:
  shared:
    name: ${DOCKER_SHARED_VOLUME}
  database:
    name: ${DOCKER_DB_VOLUME}

networks:
  inception:
    name: ${DOCKER_NETWORK}
